"""Declarative configuration: schemas, allowlist registry, loader and policy."""

from __future__ import annotations

from .active_scope import (
    ACTIVE_HANDS,
    DEFAULT_ROBOT_PROFILES,
    GOVERNING_DECISION,
    HISTORICAL_THREE_HAND_ARTIFACTS,
    KNOWN_HANDS,
    PAUSED_HANDS,
    PAUSED_ROBOT_PROFILES,
    ScopeViolation,
    WorkloadScope,
    audit_selection,
    hand_of_profile,
    historical_reproduction_scope,
    is_active,
    is_paused,
    profile_of_hand,
    require_release_scope,
    resolve_workload_hands,
)
from .loader import (
    dump_document,
    load_data_config,
    load_document,
    load_model_config,
    load_robot_config,
    load_run_config,
    load_versioned_document,
    parse_versioned_document,
    parse_document,
    preset_names,
    read_yaml_mapping,
    resolve_document_path,
)
from .policy import Adjustment, EffectiveRuntime, resolve_runtime
from .registry import (
    RegistryError,
    get_dataset_builder,
    get_document_model,
    get_model_builder,
    register_dataset,
    register_document_schema,
    register_model,
    registered_datasets,
    registered_document_schemas,
    registered_models,
)
from .schema import (
    DATA_SCHEMA_V1,
    MODEL_SCHEMA_V1,
    ROBOT_SCHEMA_V1,
    RUN_SCHEMA_V1,
    SUPPORTED_SCHEMAS,
    ConfigError,
    DataConfig,
    ModelConfig,
    RobotConfig,
    RunConfig,
)

__all__ = (
    "ACTIVE_HANDS",
    "DATA_SCHEMA_V1",
    "DEFAULT_ROBOT_PROFILES",
    "GOVERNING_DECISION",
    "HISTORICAL_THREE_HAND_ARTIFACTS",
    "KNOWN_HANDS",
    "MODEL_SCHEMA_V1",
    "PAUSED_HANDS",
    "PAUSED_ROBOT_PROFILES",
    "ROBOT_SCHEMA_V1",
    "RUN_SCHEMA_V1",
    "SUPPORTED_SCHEMAS",
    "Adjustment",
    "ConfigError",
    "DataConfig",
    "EffectiveRuntime",
    "ModelConfig",
    "RegistryError",
    "RobotConfig",
    "RunConfig",
    "ScopeViolation",
    "WorkloadScope",
    "audit_selection",
    "dump_document",
    "get_dataset_builder",
    "get_document_model",
    "get_model_builder",
    "hand_of_profile",
    "historical_reproduction_scope",
    "is_active",
    "is_paused",
    "load_data_config",
    "load_document",
    "load_model_config",
    "load_robot_config",
    "load_run_config",
    "load_versioned_document",
    "parse_versioned_document",
    "parse_document",
    "preset_names",
    "profile_of_hand",
    "read_yaml_mapping",
    "register_dataset",
    "register_document_schema",
    "register_model",
    "registered_datasets",
    "registered_document_schemas",
    "registered_models",
    "require_release_scope",
    "resolve_document_path",
    "resolve_runtime",
    "resolve_workload_hands",
)
